version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/movie-dashboard-frontend
    container_name: react-frontend
    volumes:
      - ./frontend/movie-dashboard-frontend:/app
    ports:
      - "3000:5000"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql-db
    env_file:
      - .env.db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
